### ISSUE TITLE
first question

### ISSUE THREAD

**Issue by Minhhok** [360NENZ/LDAsuku-soggy#3]
Hello im a new, my first question is does it requests grassclipper?

**Comment by Minhhok** [comment]
Second question: soggy.exe says: "game listening on port 22102" what does it means?

**Comment by 360NENZ** [comment]
1.soggy is **independent**, it does not need other.
2.`game listening on port 22102` means that soggy's simulated CBT1 server starts on port `127.0.0.1:22102`. You need to use the proxy tool to proxy the address of mihoyo/hoyoverse to port `22102` at `127.0.0.1`

**Comment by Minhhok** [comment]
is it ok? https://upanh.org/image/3T5yVF 
if it is ok what is next?

**Comment by Minhhok** [comment]
Like this? https://ibb.co/xJ8B9RQ
Im very confused

**Comment by Minhhok** [comment]
> 1.soggy is **independent**, it does not need other. 2.`game listening on port 22102` means that soggy's simulated CBT1 server starts on port `127.0.0.1:22102`. You need to use the proxy tool to proxy the address of mihoyo/hoyoverse to port `22102` at `127.0.0.1`

or like this? https://ibb.co/XSYMcnM
i still dont get it
