### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Minhhok** [360NENZ/LDAsuku-soggy#4]
I followed "How to use" but it is still doesnt work
https://www.youtube.com/watch?v=pIYDwogjUR0

**Comment by 360NENZ** [comment]
You should make sure that `dispatch.py` keeps running and outputting instead of crashing

**Comment by 360NENZ** [comment]
You can try to run `dispatch.py` in `cmd.exe` to see if there is an error in the python output. If there is an error, you may be able to solve it through Google

**Comment by Minhhok** [comment]
THank you so much i managed to dispatch.py function and it works
